[package]
name = "pomo-rs"
version = "0.1.0"
authors = ["Manikandan Sundararajan <tsmanikandan@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.16"
indicatif = "0.15.0"